FSM:
  _: # enabled fsms
    Passive:
      id: 1
    FixStand:
      id: 2
    Velocity:
      id: 3
      type: RLBase
  Passive:
    transitions: 
      FixStand: b.on_pressed
    mode: [ # motor mode
      10,10,10,10,1,1,
      10,10,10,10,1,1,
      10,
      1,1,1,1,1,1,1,
      1,1,1,1,1,1,1
    ]
    kd: [
      5,5,6,5,5,6,
      5,5,5,
      5,
      2,2,
      2,2,2,2,
      2,2,2,2, 
    ]
  FixStand:
    transitions: 
      Passive: a.on_pressed
      Velocity: x.on_pressed
    kp: [
      250, 250, 250, 400, 80, 40,
      250, 250, 250, 400, 80, 40,
      600,
      250, 400, 80, 80, 20, 20, 20,
      250, 400, 80, 80, 20, 20, 20,
    ]
    kd: [
      6.5, 6.5, 6.5, 10, 1.5, 0.4,
      6.5, 6.5, 6.5, 10, 1.5, 0.4,
      6,
      6, 10, 2, 2, 0.5, 0.5, 0.5,
      6, 10, 2, 2, 0.5, 0.5, 0.5,
    ]
    ts: [0, 3]
    qs: [
      [],
      [ 0.0, -0.1, 0.0, 0.3, -0.2, -0.2,
        0.0, -0.1, 0.0, 0.3, -0.2, -0.2,
        0.0,
        0.2, 0.0, 0.0, 0.32, 0.0, 0.0, 0.0, 
        0.2, 0.0, 0.0, 0.32, 0.0, 0.0, 0.0]

    ]
  Velocity:
    transitions: 
      Passive: a.on_pressed
    policy_dir: /home/lgcns/Humanoid/IsaacLab_New/logs/rsl_rl/unitree_h1_2_velocity_train/2026-02-05_09-56-39_basic
    